# 服务器端口
server:
  port: 80




# 数据库连接
mybatis:
  mapper-locations: classpath*:sqlmap/*.xml
  config-location: classpath:/dbconfig/mybatis-config.xml
#  # config-location 与 configuration 不能同时配置，要么使用mybatis的配置文件，要么在 yml中配置
#  configuration:
#    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl



spring:
  # 静态资源
  resources:
    # 静态资源查找路径，注意使用","号隔开 （包含 server上的文件目录）
    static-locations: classpath:/static/,file:/data/evernote/,classpath:/resources/,classpath:/sqlmap/
    # 开发环境关闭缓存
    chain:
      cache: false
    # 开启 静态资源映射处理器
    #add-mappings: true
  datasource:
    username: mysql
    password: mysql
    url: jdbc:mysql://192.168.44.101:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


  # thymeleaf模板引擎
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false


  #spring-session 使用
  session:
    store-type: none

logging:
  config: classpath:/log4j2-dev.xml




